logging.level.org.springframework.security: DEBUG
nacos:
  config:
    server-addr: 182.61.49.75:8848
    username: nacos
    password: woshidoudou
    auto-refresh: true
    enable-remote-sync-config: true
    namespace: ab00286d-00e1-4747-b1db-02cf1a0ae07f
    group: DEFAULT_GROUP
    remote-first: true
    type: properties
    max-retry: 10

lock-config:
  pattern: single #redis模式配置，single：单机模式，cluster:集群模式，replicated:云托管模式,sentinel:哨兵模式，master_slave：主从模式
  single-server:
    address: 39.108.181.13
    port: 6379
#    password: woshidoudou

spring.main:
  allow-bean-definition-overriding: true
